In [1]:
import pandas as pd

In [2]:
claims = pd.read_json (r"D:\DEPI\DEPI final project\data sources\claims.json")

In [3]:
payers = claims["payer_name"].drop_duplicates().reset_index(drop=True)
payers_df = pd.DataFrame({
    "payer_id": range(1, len(payers)+1),
    "payer_name": payers
})

In [4]:
payers_df.head()

   payer_id      payer_name
0         1     Brian Jones
1         2     Amy Collins
2         3  Christina Bell
3         4     Hunter Yang
4         5     Alan Miller

In [5]:
claims = claims.merge(payers_df, on="payer_name")

In [6]:
claims = claims.drop(columns=["payer_name"])

In [8]:
claims.head()

,claim_id,patient_id,encounter_id,amount_billed,amount_paid,status,denial_reason,payer_id
0,6DDG,41fb1477-5245-4b2c-228b-b300a0a67159,41fb1477-5245-4b2c-11f3-8a3e961cb9dc,4476.54,4218.38,paid,NaN,1
1,JAL1,6d51bacc-38ae-a901-1575-dc04723b7cbb,6d51bacc-38ae-a901-58d9-cd774da2a233,4705.65,3968.98,approved,NaN,1
2,F8T9,26ddda67-10d0-bc1a-df69-237bf9cbdef8,26ddda67-10d0-bc1a-4aed-6a30494ea43e,2437.32,0.00,denied,Duplicate claim,2
3,48KT,ffba3ef7-85cf-3a76-d6de-247f56b22c7d,ffba3ef7-85cf-3a76-69bb-9aecc803c3b0,1552.56,0.00,denied,Invalid diagnosis code,3
4,CALZ,b8721900-8733-1a11-02dd-06b897a61606,b8721900-8733-1a11-518d-1c8cf656916f,2008.42,1670.03,paid,NaN,1

In [7]:
claims.to_json(r"D:\DEPI\DEPI final project\data sources\claims_Table.json", orient="records", lines=True)

In [8]:
payers_df.to_json(r"D:\DEPI\DEPI final project\data sources\payer.json", orient="records", lines=True)